### ISSUE TITLE
`Settings.predictLabels` not defined

### ISSUE THREAD

**Issue by nylonee** [ticofab/deep-learning-with-scala#1]
Hi there, loved your talk and am trying to implement my own version of this.

I'm a bit confused as you've specified [Settings.predictLabels](https://github.com/ticofab/deep-learning-with-scala/blob/e9bd0289ce2b20f87306ba9e1f4e95f3176034ba/ModelEvaluator.scala#L74), but the definition is missing from the Settings scala file. Are you able to give an example implementation of the above?

**Comment by ticofab** [comment]
Thanks for opening this issue! I have provided an implementation of `Settings.predictLabels`. The idea is to just provide a simple 'on-the-fly' test of a few labels and print the results. Have fun and let me know if you encounter any other issues!
